
name: Generate snake game

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

            
jobs:
  build:
    name: generate-snake-game-from-github-contribution-grid
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@v3.2.0
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake2.svg
          snake_color: 'blue'

      - uses: Platane/snk@v3.2.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
