name: Update Fun Fact
# Controls when the action will run.
on:
  schedule:
      # every 12 hours
    - cron: "*/10 * * * *"

  # This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

# ... existing configuration ...

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install requests module
      run: |
        python -m pip install requests

    - name: Run Python Script
      run: |
        python .github/workflows/update_readme.py
